### ISSUE TITLE
Add Docker image build CI

### ISSUE THREAD

**Issue by peter279k** [DragonBe/vies#105]
As title, I think it should be nice to have the Docker image building with CI.

IMHO, I think we can use GitHub Actions or Travis CI to accomplish this issue.

@DragonBe, do you have any suggestion about this?

Once this issue is accepted, I think I would be happy to work on this :smile: .

**Comment by DragonBe** [comment]
Question I have is: what would you do with the container?

Option 1: run phpunit in the container
Option 2: run a web app for validating one or more VAT ID's (asynchronously)

For option 1 I run the following command to execute it with the latest PHP 7.4 stack

```sh
docker run -it --rm --name vies-test -v "$PWD":/usr/src/myapp -w /usr/src/myapp vies-php:7.4-cli vendor/bin/phpunit --no-coverage
```

This is what I also use in my internal Jenkins pipeline to ensure all is working, even in a clean environment.

For option 2, I already have a project called "[dragonbe/vies-web](https://github.com/DragonBe/vies-web)" where you can run a web interface for this service. Maybe there we could add a docker container to build and run it everywhere?

**Comment by peter279k** [comment]
@DragonBe, thanks for your reply.

Option 1: This may have some descriptions on `README` to let developers know how to run unit tests for this project with PHPUnit. 

Option 2: Yes. It may be convenient and easy for developers to run `vies-web` with Docker container everywhere.

**Comment by DragonBe** [comment]
Added a stand-alone container in #131
