### ISSUE TITLE
[Insight] Boolean should be compared strictly - in src/Vies/Vies.php, line 189

### ISSUE THREAD

**Issue by DragonBe** [DragonBe/vies#12]
**[in src/Vies/Vies.php, line 189](https://github.com/DragonBe/vies/blob/b82a473c13d45ae634d4490739a5092d697989cd/src/Vies/Vies.php#L189)**

> With booleans, only strict comparison (with `===` operator) should be used to lower bug risks and to improve performances.

```php
     *
     * @return Validator
     */
    public function getValidator()
    {
        if (null == $this->validator) {
            $this->validator = new Validator();
        }

        return $this->validator;
    }
```

---------------------

_Posted from [SensioLabsInsight](https://insight.sensiolabs.com/projects/21b019ce-dd1d-4d16-8b74-880b9ee5e795/analyses/27)_

**Comment by krzaczek** [comment]
fixed in #11
