### ISSUE TITLE
VIES_EU_COUNTRY_LIST Visibility 

### ISSUE THREAD

**Issue by blaaat** [DragonBe/vies#120]
`VIES_EU_COUNTRY_LIST `is a protected const, but all other code is using `self::VIES_EU_COUNTRY_LIST`. 

the protected visibility gives the illusion you can extend the class and for example remove UK (#98 ), but this wouldn't work. 

VIES_EU_COUNTRY_LIST should either be private or beter; other methods should use: `static::VIES_EU_COUNTRY_LIST`

**Comment by DragonBe** [comment]
Not going to make them static
