### ISSUE TITLE
Implementing a Symfony constraint based on this library

### ISSUE THREAD

**Issue by johanwilfer** [DragonBe/vies#125]
We have been using this great library for a while now, and I have begun to extract some code we have in a few classes for this to something more generic and useful. Today we are using Symfony and a callback validator, but I am extracting it into a separate class like described here: https://symfony.com/doc/current/validation/custom_constraint.html

Would a PR be welcome with this functionality? Any pointers on how / where you like it?
I am thinking it will take a string input like this `SE12345678901` and do the validation using this library.

**Comment by DragonBe** [comment]
As mentioned in the [README](../README.md), there is already a Symfony bundle available. See [MyOnlineStore ViesBundle](https://github.com/MyOnlineStore/ViesBundle).

**Comment by johanwilfer** [comment]
Ah, I missed that. Thanks! Will close this and make a PR for that library instead then.
