### ISSUE TITLE
Add support for United Kingdom (Northern Ireland) ("GB-NIR")

### ISSUE THREAD

**Issue by jonathanmaron** [DragonBe/vies#127]
> In accordance with the agreed Protocol on Ireland and Northern Ireland following Brexit, EU customs rules and procedures generally continue to apply to goods entering and leaving Northern Ireland.

Source: https://ec.europa.eu/taxation_customs/uk_withdrawal_en

We therefore should add support for the "United Kingdom (Northern Ireland)".
 
Since the new XI VAT numbers for Northern Ireland businesses are just like the GB VAT numbers, we should be able to re-purpose the current GB validator:

> Businesses should substitute "XI" country code in their GB VAT number on invoices so that the transactions can be identified separate from UK VAT transactions. So XI 123456789 - instead of GB 123456789. 

Source (and other details): https://www.avalara.com/vatlive/en/vat-news/brexit-northern-ireland-vat-and-eoro--xi--number.html

**Comment by DragonBe** [comment]
Yes @jonathanmaron, you're absolutely correct. I suggest that before we remove UK completely (#126) we should first look at integrating Northern Ireland correctly.

What I'm missing in the documentation up to this point are the structure definition and which calculation method is being used to verify if this new VAT ID is formatted correctly. Do you have some details about that?

**Comment by jonathanmaron** [comment]
I would agree with you to add "United Kingdom (Northern Ireland)" before we remove "United Kingdom".

The only documentation that I found on the structure of the new XI VAT numbers is at:

https://www.avalara.com/vatlive/en/vat-news/brexit-northern-ireland-vat-and-eoro--xi--number.html

> The UK and EU have agreed the above transactions should use the "XI" country code instead of "GB" for VAT numbers on invoices and statistical declarations. [..] Businesses should substitute "XI" country code in their GB VAT number on invoices so that the transactions can be identified separate from UK VAT transactions. So XI 123456789 - instead of GB 123456789. [..] There is no requirement to apply for a new "XI" VAT number. Businesses with NI postcodes will automatically be assumed to be operating within the terms of the NI Protocol.

According to that, we can simply re-purpose the current "United Kingdom" validator.

**Comment by DragonBe** [comment]
Yes, this can be done. Do you want to replicate the UK validator for Northern Ireland @jonathanmaron, including the tests?

**Comment by jonathanmaron** [comment]
It would be my pleasure to implement the require classes.

**Comment by jonathanmaron** [comment]
And done. See pull request https://github.com/DragonBe/vies/pull/128

**Comment by jonathanmaron** [comment]
If you search for some town names in Northern Ireland in the "Enter company name" text entry box at http://www.vat-check.co.uk you can find some real VAT numbers belonging to Northern Ireland businesses. Simply replace "GB" with "XI" for test purposes.

**Comment by DragonBe** [comment]
Merged #128 after updating GitHub Action to test against PHP 7.4 as some components are not yet ready for PHP 8 unfortunately.
