### ISSUE TITLE
[Insight] Usage of a function in loops should be avoided - in src/Vies/Validator.php, line 445

### ISSUE THREAD

**Issue by DragonBe** [DragonBe/vies#13]
**[in src/Vies/Validator.php, line 445](https://github.com/DragonBe/vies/blob/b82a473c13d45ae634d4490739a5092d697989cd/src/Vies/Validator.php#L445)**

> This loop uses a function. To avoid the overhead of executing the function n times, you should precalculate it before the loop.

```php
            return false;
        }
        $weights = array(6, 5, 7, 2, 3, 4, 5, 6, 7);
        $checksum = (int)$vatNumber[9];
        $checkval = 0;
        for ($i = 0; $i < count($weights); $i++) {
            $checkval += (int)$vatNumber[$i] * $weights[$i];
        }
        $checkval = $checkval % 11;
        if ($checkval != $checksum) {
            return false;
```

---------------------

_Posted from [SensioLabsInsight](https://insight.sensiolabs.com/projects/21b019ce-dd1d-4d16-8b74-880b9ee5e795/analyses/27)_

**Comment by krzaczek** [comment]
fixed in #11
