### ISSUE TITLE
Add cache, to save traffic to VIES service and improve performance

### ISSUE THREAD

**Issue by jonathanmaron** [DragonBe/vies#16]
There are applications in which a VAT number may need to be checked more than once per day (customer makes multiple purchases in short period of time).

Do you think it would make sense to add a cache in order to reduce the traffic to the backend service and further improve performance.

A TTL of 1 day as default would make sense, in my opinion.

What do you think?

**Comment by DragonBe** [comment]
Hi @jonathanmaron,

Caching is a good idea, but I don't think it's the goal of this package to provide integrated cache as everyone implements their own cache.

What I suggest is that you within your app implement cache for a TTL of 1 day on the validation response of this VIES service. Example below.

```php
// We instantiate the VIES service (or use DI)
$vies = new DragonBe\Vies\Vies();

// We create a unique cache key based on the country code and VAT number
$cacheKey = $countryCode . $vatNumber;

// Cached data is an array formed by $cacheKey and the VAT validation result
$cacheHit = [$cacheKey => false];

// Our cache routine
if (false === ($cacheHit = $this->getCache()->load($cacheKey))) {
    try {
        $validationResult = $vies->validateVat($countryCode, $vatNumber);

        // Since the cache also returns false on a cache miss, we need to be creative
        // storing the result.
        $this->getCache()->save($cacheKey, [$cacheKey => $validationResult]);
    } catch (SoapException $soapException) {
        $this->getLogger()->crit($soapException->getMessage());
    }
}

return $cacheHit[$cacheKey]; // returns true or false
```

I hope this makes sense for you. Let me know if it doesn't.

**Comment by jonathanmaron** [comment]
Thanks for the update. I think that a cache is very important, but you are right, it can be implemented one level higher in the application logic. Thanks for the sample code. :-) Jonathan
