### ISSUE TITLE
Improve quality of VAT validation -- companyCountryCode

### ISSUE THREAD

**Issue by jonathanmaron** [DragonBe/vies#21]
Before we know whether to ask a customer for a VATIN, we have to first find out in which country his or her company is registered. If this country code is one of the 28 EU member states, then we should ask the customer for a VATIN in a B2B application.

Therefore, we know to which member state a VATIN should belong. For example, a German company (countryCode: DE), must enter a VATIN starting with "DE". Similarly, a Belgium company (countryCode: BE) must enter a VATIN starting with "BE".

As everyone validating VATINs has to implement this logic in his or her own program code, I feel it would be useful for DragonBe\Vies to accept a "companyCountryCode" i.e. the code of the country of the customer's registered company. In the case that the "companyCountryCode" does not match the country code of the VATIN, then an error would be raised before the validateVatSum() stage, and certainly before speaking to the SOAP service.

What do you think?

**Comment by DragonBe** [comment]
Hey @jonathanmaron,


There's a bit of more complexity than just meets the eye, if you really want to apply it for a B2B approach. As a company in the EU we can optain VAT registrations in more countries than just our own. Example is [https://www.phpbenelux.eu](PHPBenelux): registered in the NL but with a NL and a BE VAT identification number. 

If I follow your train of thoughts I can check if NL (HQ of PHPBenelux) is an EU country, but assuming I'm validating a Dutch VAT Identification Number is not right in this case.

A better suggestion would be to have the B2B application check where the client company is located and on basis of this offer the validation of VAT.

Registration of new client:
- in EU? VAT requires validation
- not in EU? Other rules
