### ISSUE TITLE
Irish VAT numbers can be 8 OR 9 characters

### ISSUE THREAD

**Issue by mclemme** [DragonBe/vies#22]
VAT numbers from Ireland (IE) can be [9 characters long](https://www.meridianglobalservices.com/blog/2013/01/01/New-tax-number-format-Ireland) - but the ValidatorIE class expects a length of 8.

```
if (strlen($vatNumber) != 8) {
    return false;
}
```

Which makes 9 character valid Irish VAT numbers fail a validation.

I've forked the repo and will look into fixing this and making a pull request once it's working.

EDIT: Another source for the [8 OR 9 length](https://www.gov.uk/guidance/vat-eu-country-codes-vat-numbers-and-vat-in-other-languages).

**Comment by DragonBe** [comment]
I'm sorry @mclemme, it has been really busy lately and I haven't had time to read your concern.

So, the length is now 8 or 9, right? Let me see if I can fix it.

Thank you for the heads-up and again my sincere apologies for ignoring your feedback this long, it is very much appreciated.

**Comment by DragonBe** [comment]
Hey @mclemme,

The link you provided states:
> Ireland (IE)	1234567X, 1X23456X, 1234567XX, (8 or 9 characters. Includes one or two alphabetical characters (last, or second and last, or last 2))

But the official [EC VIES documentation](http://ec.europa.eu/taxation_customs/vies/faqvies.do#item16) is mentioning only two of the three structures.
> IE-Ireland	IE9S99999L IE9999999WI	1 block of 8 characters or 1 block of 9 characters

What I'm going to do is to implement the official structures mentioned on the EC VIES documentation. I think that the documentation reflects the accepted values on their service.

**Comment by krzaczek** [comment]
@DragonBe 

This is the official info about the change http://www.revenue.ie/en/practitioner/ebrief/archive/2013/no-032013.html

I'll try to implement it till the end of the week
