### ISSUE TITLE
Invalid VAT number doesn't mean that it's not real ;-)

### ISSUE THREAD

**Issue by michalsingr** [DragonBe/vies#38]
https://github.com/DragonBe/vies/blob/c367d119bac21d921a9f5f06e479f82f4183ce6c/src/Vies/Vies.php#L222

This condition might be tricky... As my second test I've tried VAT `CZ27082440` (the biggest e-shop in our country) which was evaluated by `validateVatSum()` method as invalid but it's existing and can be properly checked via VIES website.

I understand that the purpose of this is probably reducing requests to VEIS but IMHO I would not trust any EU administrator that a pattern (probably defined by law) for VAT number was fulfilled. As a result of this condition we get faked data, not real data from VIES.

Removing this condition or making it optional would help.

**Comment by krzaczek** [comment]
@michalsingr Just pushed a patch to fix this issue. Maybe it's a good idea to add a switch that would allow to disable check-sum checking and relay 100% on the VIES API.

@DragonBe
