### ISSUE TITLE
validateVatSum method falsly returns false for spanish VAT number

### ISSUE THREAD

**Issue by hvanoch** [DragonBe/vies#41]
Vat number ESX5910266W is valide according to the VIES service. But the validateVatSum method returns false.

**Comment by DragonBe** [comment]
@hvanoch Thank you for reporting this issue. 

Unfortunately I don't have much free time to spend on this issue, but I will try to look into this in the next 2 weeks.

**Comment by krzaczek** [comment]
I can look at it tommorow

pawel (at) mobile

**Comment by DragonBe** [comment]
@krzaczek That would be so awesome! Thank you!

**Comment by krzaczek** [comment]
Found some free time in between other tasks 👍

**Comment by DragonBe** [comment]
Awesome work @krzaczek for your "some free time". Thank you so much for making this tool so much better.
