### ISSUE TITLE
This is more of a question than an issues - per country validation

### ISSUE THREAD

**Issue by jellyNoone** [DragonBe/vies#88]
Hi, I was just going through your code and I really like the work you did with the per country pre VIES validation. I was just wondering where did you get the information on the structure of the VAT IDs. If you don't mind sharing

**Comment by krzaczek** [comment]
Most of the work is based on this document https://github.com/phax/ph-masterdata/blob/master/ph-masterdata/docs/VIES-VAT%20Validation%20Routines-v15.0.pdf

**Comment by krzaczek** [comment]
and https://ec.europa.eu/taxation_customs/tin/specs/FS-TIN%20Algorithms-Public.docx

**Comment by jellyNoone** [comment]
Thank you! I wrote them an email asking if such document exists. And they said it didnt.
