### ISSUE TITLE
Dutch Sole trader VAT number changed (2020).

### ISSUE THREAD

**Issue by Smitsel** [DragonBe/vies#89]
For sole traders in the netherlands the format for VAT number changed.
We've now hotfixed this by removing the checksum check in the ValidatorNL.

I could not find a clear picture of how to checksum check these new VAT numbers yet.

**Comment by krzaczek** [comment]
@Smitsel Could You provide an example VAT number that validates in VIES and does not pass a checksum test ?

**Comment by Smitsel** [comment]
Yes, for example: NL000099998B57

Taken from: https://www.belastingdienst.nl/wps/wcm/connect/nl/btw/content/gebruik-vanaf-1-januari-2020-uw-nieuwe-btw-identificatienummer

I can not disclose any real VAT numbers ofcourse.

**Comment by MollieRick** [comment]
I can disclose my VAT number: **NL002342672B42**

**Comment by krzaczek** [comment]
@MollieRick thx. Yep Your number validates in VIES but there is no information on the new algorithm to calculate the checksum. I'll try to google a little bit more but i may be easier to look for it in Dutch rather than in English ;)

**Comment by Smitsel** [comment]
We've looked for it as well, could not find any information about calculating the checksum.
I will try to find a contact with the dutch government.

**Comment by krzaczek** [comment]
Found it: http://kleineondernemer.nl/index.php/nieuw-btw-identificatienummer-vanaf-1-januari-2020-voor-eenmanszaken

**Comment by krzaczek** [comment]
Yep it works more **2321**002342672**11**42 % 97 = 1 - so it's correct. Now I just need to find a way to distinguish old numbers from the new one's so that both validate ;)

**Comment by Smitsel** [comment]
If they can't be differentiated you could do it by doing this check when the first one fails. 
So in a failover kind of way.

**Comment by Smitsel** [comment]
We can totally review your PR once you have something too btw.

**Comment by krzaczek** [comment]
That's my plan . I will validate the TIN against both algo. If the first one fails -> will try the new one

**Comment by krzaczek** [comment]
Waiting for code review ....

**Comment by Smitsel** [comment]
Awesome, i left some not super important comments. It works as intended, i've tried it out in our fork.

**Comment by DragonBe** [comment]
Sorry being late at the game, this holiday time is for me the only time I can truly spend with my family in full. But now when they're off playing games themselves, I can have a look at this.

**Comment by krzaczek** [comment]
@Smitsel should be fine one. I did add a regex expression to check i the number has only valid characters before calculating checksum [0-9A-Z=*]. This way it should be safer. In the older version there was a small % of chance that a number with an invalid char would validate :) It would then error on VIES but still :)

**Comment by Smitsel** [comment]
Many thanks for the fast fix! 🥇

**Comment by AleksanderGladkov** [comment]
Found this page in google, thanks to all participants for the information.
To those who also gets to this page, here is my version of this algorithm in C#. The simple conversion of VAT number to integer can cause overflow error, because the maximum length of converted VAT number is 26, while the max length of ulong type in C# is 20. Therefore I write converted VAT number to a string first and then subsequently convert the string to an integer and divide it by 97.

```
public void ValidateVatMod97Algorithm(string vat) {
    if (vat.Length != 14) {
        throw new System.Exception("VAT must have exactly 14 chars");
    }

    if (vat.Substring(0, 2) != "NL") {
        throw new System.FormatException("First two chars must be NL");
    }
    
    if (!char.IsDigit(vat[12]) || !char.IsDigit(vat[13])) {
        throw new System.FormatException("Last two chars must be digits");
    }
    // we can also check that the two-digit number in the end is between 02 and 98.
    
    var sb = new StringBuilder();
    foreach (char ch in vat) {
        int currNumber = 0;

        if (char.IsDigit(ch)) currNumber = ch - '0';
        else if (char.IsUpper(ch)) currNumber = ch - 55;
        else if (ch == '+') currNumber = 36;
        else if (ch == '*') currNumber = 37;
        else throw new System.FormatException("VAT contains incorrect chars");

        sb.Append(currNumber);
    }

    string vatDigitString = sb.ToString();
    int remainder = 0;
    foreach (char ch in vatDigitString) {
        int digit = ch - '0';
        remainder = (remainder * 10 + digit) % 97;
    }

    if (remainder != 1) {
        throw new System.FormatException("VAT is not valid according to the Modulus-97 checksum algorithm.");
    }
}
```
