### ISSUE TITLE
Invalidate old Dutch OB numbers in favour of new VAT ID as of 2020

### ISSUE THREAD

**Issue by DragonBe** [DragonBe/vies#93]
Since January 1, 2020 self employed people in the Netherlands received a new VAT identification number as replacement for their older number which contained their social security number (BSN).

In release 2.1.10 we made changes to allow this new number to be validated, but we left out the invalidation of the old number as it now is called "omzetbelastingnummer" or OB number.

On [kleineondernemer.nl](http://kleineondernemer.nl/index.php/nieuw-btw-identificatienummer-vanaf-1-januari-2020-voor-eenmanszaken) (Dutch) they describe how to invalidate these OB numbers.

As they describe it (translated by me):

For natural people the number looks like the following starting from 01-01-2020;

- position 1 - 2; the country code
- position 3 - 11; 9 numbers. This series of numbers **never** confirms to the so called eleven proof.
- position 12; the letter "B"
- position 13 - 14; 2 numbers. Control number confirms to modulo 97 over the whole number

Which means the old OB number which contains the social security number should now be checked against the [eleven proof](http://ha1.heartprofit.nl/profit/index.php?topic=13548.0;wap2).

We now need to invalidate those Dutch VAT numbers that still confirm to the 11 proof as they contain the social security numbers which is a violation against GDPR.

**Comment by krzaczek** [comment]
Well we actually can't. The old numbers user the same algo as VAT commercial numbers. We still need to validate the old method otherwise a VAT number of a  hotel would not pass a checksum validation.

NL824155890B08 - this is a random VAT number of a hotel in Amsterdam. It uses the same MOD 11 method to calculate a checksum as old OB numbers.

From what i've read there is no way to say if the specified VAT number is a commercial one or an old OB  number

**Comment by DragonBe** [comment]
If we cannot make the distinction we cannot prevent people from validating a now invalid VAT ID (OB number) against the VIES service where it will be marked as invalid.

Guess we should mention in our documentation that we cannot make the distinction on our end and the only way to actually validate Dutch VAT ID's is by using the VIES service through our library.

What a pitty, but we can only do so much right?

**Comment by jrfnl** [comment]
> we cannot make the distinction on our end and the only way to actually validate Dutch VAT ID's is by using the VIES service through our library.

That sounds about right.

Also: I just ran a little test with my own VAT numbers with the [VIES service](http://ec.europa.eu/taxation_customs/vies/) which I presume you are using as an end-point and it correctly validates the new number and marks the old number as invalid.

**However**, this also means that for people who don't do their accounting on a daily basis and retroactively need to check an old Dutch VAT number, there is currently no way to validate this anymore.... and this of course would also apply to applications doing a bulk check of the VAT numbers once in a while.

**Comment by DragonBe** [comment]
That sounds about correct @jrfnl. This VIES library pre-validates VAT ID's before they are send to the official VIES service provided by the European Commission. It allows people to perform their required validation checks for their suppliers and clients and offers a way to do this offline because the official service is known to have stability and uptime issues.

I feel that by not having the ability to disallow OB numbers to be marked valid we're not giving our users the value they need. The Dutch Tax Office implemented this change starting the beginning of the year, but it will require lots of time for people to change their habbits and their stack of pre-printed invoice and order papers.

I will close this issue now as there's not much we can do on our side to reject OB-numbers, but if the situation changes in the future I would be very happy re-open this issue.

Thank you @krzaczek and @jrfnl for your input, very much appreciating your thoughts on this.

**Comment by jrfnl** [comment]
@DragonBe Sorry I couldn't be of more help or offer a solution. If I hear of anything which could help I'll post it here.

**Comment by jrfnl** [comment]
> The Dutch Tax Office implemented this change starting the beginning of the year, but it will require lots of time for people to change their habbits and their stack of pre-printed invoice and order papers.

Regarding this: as far as I know everyone whose VAT number has changed got a letter about this already some two months ago with the new number. This was done explicitly to allow them to their (pre-printed) paperwork sorted before January 1st, as well as inform their regular suppliers.
