### ISSUE TITLE
ValidatorFI::validate returns false for valid FI VAT number

### ISSUE THREAD

**Issue by sophiekuehn** [DragonBe/vies#95]
ValidatorFI::validate returns false for valid FI VAT number
FI 01089940

Valid according to http://ec.europa.eu/taxation_customs/vies/vatResponse.html

**Comment by krzaczek** [comment]
@sophiekuehn i'll look at it in the evening

**Comment by jbrinksmeier** [comment]
hi @krzaczek  co-worker of sophie here. I had a quick look already and stumbled across ValidatorFI rules

> VAT format: [C1 C2 C3 C4 C5 C6 C7 C8]
>  
> Range:
>       C2 .. C8 Numeric from 0 to 9
> 
> Rules:
>  C8
>       R = 11 - (7*C1 + 9*C2 + 10*C3 + 5*C4 + 8*C5 + 4*C6 + 2*C7) modulo11
>       If R = 10 then, VAT number is invalid
>       If R = 11 then C8 = 0
>       Else C8 = R

I read it like R=11 AND C8=0 is a valid VAT for Finland, but the code does not reflect this but only the last case ELSE C8 = R
At least that's how I read 
`return 11 - ($checkval % 11) == (int) $vatNumber[7];` 
If yo agree I can prepare a PR for this.
Thanks for your efforts :)

**Comment by krzaczek** [comment]
Feel free to make a PR. I’ll look at it in the evening 

pawel (at) mobile

**Comment by DragonBe** [comment]
Fixed in #96 and tagged as [release 2.1.11](https://github.com/DragonBe/vies/releases/tag/2.1.11). Closing this issue now.
