### ISSUE TITLE
Vat ID no longer valid

### ISSUE THREAD

**Issue by jellyNoone** [DragonBe/vies#97]
Hi,
your testing Vat id for SI 15012557 is invalid.

**Comment by krzaczek** [comment]
Hi,

Well that's true it's not valid according to VIES, but we only use it to verify if the algorithm to check the checksum is correct. So the number `SI15012557` is still checksum valid even if VIES says it's not "active"

**Comment by jellyNoone** [comment]
Oh ok, 
thanks for clarifying.
