### ISSUE TITLE
Remove Validation of VAT Numbers from Great Britain

### ISSUE THREAD

**Issue by jonathanmaron** [DragonBe/vies#98]
Following [Brexit](https://www.bbc.com/news/world-europe-51307874) on January 31, 2020 (23:00 London time), Great Britain is no longer part of the European Union. Consequently, this component no longer needs to validate VAT numbers from Great Britain.

**Comment by ShinJii89** [comment]
But it's in VIES until end of 2020 or 2024 (I don't remember).

**Comment by cottton** [comment]
I read until end of 2020 nothing changes vat vise.

Source: https://www.heise.de/newsticker/meldung/Keine-Partystimmung-zum-Brexit-Gefahr-eines-No-Deals-nicht-gebannt-4650605.html?seite=2

> Zentraler Punkt im Austrittsvertrag ist eine Übergangsfrist bis zum Jahresende, in der sich im Alltag fast nichts ändert. Großbritannien bleibt in der Zeit im EU-Binnenmarkt und in der Zollunion.

**Comment by DragonBe** [comment]
What we can do is start marking the usage of the "GB" validator as `@deprecated` but I wouldn't jump ship yet by removing it completely from the codebase.

Thoughts and ideas about this please.

**Comment by Seldaek** [comment]
I don't think anything needs to change for now, or if anything it should be within an `if (date('Ym') >= '202101') { ... }`, but we'll probably know more about this later in the year.

**Comment by DragonBe** [comment]
I will close this issue for the time being, if regulations change I will reopen it and perform the necessary changes.

**Comment by blaaat** [comment]
> I will close this issue for the time being, if regulations change I will reopen it and perform the necessary changes.

I believe the transition period can't be extended anymore. So UK is leaving the VAT territory on dec 31th.

The date check on `listEuropeanCountries()` sounds perfect.
